apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wccq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0047-tenant/tkwch-fix-0075-0047-app/devfile-sample-wccq@sha256:c99182dd6bdfac33d9f3efc720eb0f9ed50c0d09885803725a880cf857c0f4db
        name: my-nodejs
        resources: {}
status: {}
